# Generated by Django 6.0.1 on 2026-03-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('SHIPPED', 'Đang giao hàng'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
