# Generated by Django 6.0.1 on 2026-03-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('charger_type', models.CharField(choices=[('DC_FAST', 'DC Fast'), ('AC_SLOW', 'AC Slow'), ('SUPERCHARGER', 'Supercharger')], default='DC_FAST', max_length=20)),
                ('power', models.CharField(default='50kW', max_length=20)),
                ('total_ports', models.PositiveIntegerField(default=0)),
                ('available_ports', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('MAINTENANCE', 'Bảo trì'), ('INACTIVE', 'Ngừng hoạt động')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
