# Generated by Django 6.0.1 on 2026-03-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_chargingstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stations/'),
        ),
    ]
